In [1]:
# Linear Regression
# Application: House Price Prediction

import numpy as np
from sklearn.linear_model import LinearRegression

print("----- Linear Regression -----")

# Training Data
# House Size (sq.ft)
X_linear = np.array([
    [1000],
    [1200],
    [1500],
    [1800],
    [2000]
])

# House Prices (Lakhs)
y_linear = np.array([
    50,
    55,
    65,
    80,
    90
])

# Create Model
linear_model = LinearRegression()

# Train Model
linear_model.fit(X_linear, y_linear)

# Predict Price for New House
new_house_size = np.array([[1700]])
predicted_price = linear_model.predict(new_house_size)

print("Training House Sizes:")
print(X_linear.flatten())

print("\nTraining House Prices:")
print(y_linear)

print("\nPredicted Price for 1700 sq.ft house:")
print(predicted_price[0])

----- Linear Regression -----
Training House Sizes:
[1000 1200 1500 1800 2000]

Training House Prices:
[50 55 65 80 90]

Predicted Price for 1700 sq.ft house:
76.08823529411764


In [2]:
# Logistic Regression
# Application: House Purchase Classification

import numpy as np
from sklearn.linear_model import LogisticRegression

print("----- Logistic Regression -----")

# Training Data
# House Prices (Lakhs)
X_logistic = np.array([
    [40],
    [50],
    [60],
    [70],
    [80],
    [90]
])

# Labels
# 0 = Not Purchased
# 1 = Purchased
y_logistic = np.array([
    0,
    0,
    0,
    1,
    1,
    1
])

# Create Model
logistic_model = LogisticRegression()

# Train Model
logistic_model.fit(X_logistic, y_logistic)

# Test House Price
test_price = np.array([[75]])

# Prediction
purchase_prediction = logistic_model.predict(test_price)

# Probability
purchase_probability = logistic_model.predict_proba(test_price)

print("Training House Prices:")
print(X_logistic.flatten())

print("\nPurchase Labels:")
print(y_logistic)

print("\nTest House Price:")
print(test_price[0][0])

print("\nPurchase Prediction:")
print(purchase_prediction[0])

print("\nPrediction Probabilities:")
print(purchase_probability)

----- Logistic Regression -----
Training House Prices:
[40 50 60 70 80 90]

Purchase Labels:
[0 0 0 1 1 1]

Test House Price:
75

Purchase Prediction:
1

Prediction Probabilities:
[[0.00349394 0.99650606]]
