In [2]:
# Bernoulli Distribution
# Application: Student Exam Pass/Fail Analysis

from scipy.stats import bernoulli

print("----- Bernoulli Distribution -----")

# Probability of passing
p = 0.7

# Generate random outcomes for 10 students
# 1 = Pass, 0 = Fail
bernoulli_samples = bernoulli.rvs(p, size=10)

print("Probability of Passing:", p)
print("Student Outcomes (1=Pass, 0=Fail):")
print(bernoulli_samples)

# Probability of success
print("\nProbability of Pass:")
print(bernoulli.pmf(1, p))

# Probability of failure
print("Probability of Fail:")
print(bernoulli.pmf(0, p))

----- Bernoulli Distribution -----
Probability of Passing: 0.7
Student Outcomes (1=Pass, 0=Fail):
[1 1 1 1 1 1 1 0 0 1]

Probability of Pass:
0.7
Probability of Fail:
0.30000000000000004


In [3]:
# Binomial Distribution
# Application: Student Exam Pass/Fail Analysis

from scipy.stats import binom

print("----- Binomial Distribution -----")

# Number of students
n = 10

# Probability of passing
p = 0.7

# Exactly 8 students pass
k = 8

# Calculate probability
binomial_probability = binom.pmf(k, n, p)

print("Number of Students:", n)
print("Probability of Passing:", p)

print(f"\nProbability that exactly {k} students pass:")
print(binomial_probability)

# Random experiment (5 trials)
random_binomial = binom.rvs(n, p, size=5)

print("\nRandom Binomial Outcomes:")
print(random_binomial)

----- Binomial Distribution -----
Number of Students: 10
Probability of Passing: 0.7

Probability that exactly 8 students pass:
0.23347444050000013

Random Binomial Outcomes:
[7 9 7 8 6]


In [4]:
# Z-Test
# Application: Student Performance Analysis

import numpy as np
from statsmodels.stats.weightstats import ztest

print("----- Z-Test -----")

# Sample marks
sample_marks = np.array([78, 82, 85, 88, 90, 76, 95, 89, 84, 91])

# Population mean
population_mean = 80

# Perform Z-test
z_stat, p_value = ztest(sample_marks, value=population_mean)

print("Sample Marks:")
print(sample_marks)

print("\nPopulation Mean:", population_mean)
print("\nZ-Statistic:", round(z_stat, 3))
print("P-Value:", round(p_value, 4))

alpha = 0.05

if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")

----- Z-Test -----
Sample Marks:
[78 82 85 88 90 76 95 89 84 91]

Population Mean: 80

Z-Statistic: 3.078
P-Value: 0.0021

Result: Reject Null Hypothesis


In [1]:
# Independent t-Test
# Application: Student Performance Analysis

import numpy as np
from scipy import stats

print("----- Independent t-Test -----")

# Marks of two classes
class_A = np.array([78, 82, 85, 88, 90])
class_B = np.array([72, 75, 70, 68, 74])

# Perform Independent t-test
t_stat, p_value = stats.ttest_ind(class_A, class_B)

print("Class A Marks:")
print(class_A)

print("\nClass B Marks:")
print(class_B)

print("\nt-Statistic:", round(t_stat, 2))
print("P-Value:", round(p_value, 4))

alpha = 0.05

if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")

----- Independent t-Test -----
Class A Marks:
[78 82 85 88 90]

Class B Marks:
[72 75 70 68 74]

t-Statistic: 5.14
P-Value: 0.0009

Result: Reject Null Hypothesis
