In [1]:
# Decision Tree Classification
# Application: Student Pass/Fail Prediction

import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("----- Decision Tree Classification -----")

# Training Data
# Features: [Study Hours, Attendance Percentage]
X = np.array([
    [2, 50],
    [3, 60],
    [4, 65],
    [5, 70],
    [6, 75],
    [7, 80],
    [8, 85],
    [9, 90]
])

# Labels
# 0 = Fail
# 1 = Pass
y = np.array([0, 0, 0, 1, 1, 1, 1, 1])

# Train Model
model = DecisionTreeClassifier(random_state=42)
model.fit(X, y)

# Test Data
X_test = np.array([
    [3, 55],
    [5, 72],
    [8, 88],
    [4, 60]
])

# Actual Labels
y_test = np.array([0, 1, 1, 0])

# Predictions
y_pred = model.predict(X_test)

# Performance Metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

# Display Results
print("\nActual Labels:")
print(y_test)

print("\nPredicted Labels:")
print(y_pred)

print("\nConfusion Matrix:")
print(cm)

print("\nAccuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

----- Decision Tree Classification -----

Actual Labels:
[0 1 1 0]

Predicted Labels:
[0 1 1 0]

Confusion Matrix:
[[2 0]
 [0 2]]

Accuracy: 1.0
Error Rate: 0.0
Precision: 1.0
Recall: 1.0
F1-Score: 1.0


In [2]:
# K-Nearest Neighbors (KNN)
# Application: Student Pass/Fail Prediction

import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("----- K-Nearest Neighbors -----")

# Training Data
X_train = np.array([
    [2, 50],
    [3, 60],
    [4, 65],
    [5, 70],
    [6, 75],
    [7, 80],
    [8, 85],
    [9, 90]
])

# Labels
y_train = np.array([0, 0, 0, 1, 1, 1, 1, 1])

# Create KNN Model
model = KNeighborsClassifier(n_neighbors=3)

# Train Model
model.fit(X_train, y_train)

# Test Data
X_test = np.array([
    [3, 55],
    [5, 72],
    [8, 88],
    [4, 60]
])

# Actual Labels
y_test = np.array([0, 1, 1, 0])

# Predictions
y_pred = model.predict(X_test)

# Performance Metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

# Display Results
print("\nActual Labels:")
print(y_test)

print("\nPredicted Labels:")
print(y_pred)

print("\nConfusion Matrix:")
print(cm)

print("\nAccuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

----- K-Nearest Neighbors -----

Actual Labels:
[0 1 1 0]

Predicted Labels:
[0 1 1 0]

Confusion Matrix:
[[2 0]
 [0 2]]

Accuracy: 1.0
Error Rate: 0.0
Precision: 1.0
Recall: 1.0
F1-Score: 1.0
